spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:${H2_DBNAME}       # in-memory 모드 (db 종료 시 데이터 사라짐)
    url: jdbc:h2:~/${H2_DBNAME}         # embedded 모드 (db 종료 시 데이터 유지)
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true